// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dngqnvbhrsontbdmapfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuZ3FudmJocnNvbnRiZG1hcGZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNzM0NDQsImV4cCI6MjA2Njg0OTQ0NH0.JHdYArqSa3GdiTv0Vx-VgQbEOYqkLC9Jic9CRjWHoc0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});